\c ${DATABASE}

UPDATE JV_SNAPSHOT 
SET STATE = REPLACE(STATE, '${OLD_URL}/api', '${NEW_URL}/api')
WHERE MANAGED_TYPE LIKE 'edu.kit.datamanager.repo.domain.RelatedIdentifier' 
AND STATE LIKE '%${OLD_URL}/api%';

UPDATE LINKED_METADATA_RECORD
SET SCHEMA_ID = REPLACE(SCHEMA_ID, '${OLD_URL}/api', '${NEW_URL}/api')
WHERE SCHEMA_ID LIKE '${OLD_URL}/api%';

UPDATE RELATED_IDENTIFIER
SET VALUE = REPLACE(VALUE, '${OLD_URL}/api', '${NEW_URL}/api')
WHERE RELATION_TYPE LIKE 'IS_DERIVED_FROM' 
AND VALUE LIKE '${OLD_URL}/api%';

UPDATE URL2PATH
SET URL = REPLACE(URL, '${OLD_URL}/api', '${NEW_URL}/api')
WHERE URL LIKE '${OLD_URL}/api%';
